development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a7ff29838cf5d98a31731eeb06873dc3@scat.redistogo.com:10887/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: partygames_backend_production
